#! /usr/bin/env node

var Jimp = require('jimp')
var fs = require('fs')
var path = require('path')
var gm = require('gm')
var parallelLimit = require('run-parallel-limit')

let targetdir = './raw/raw'
let outdir = './raw/processed'

let files = fs.readdirSync(targetdir)
let images = files.filter(x => x.endsWith('jpg'))

let resize = (name) => {

  return function(cb) {
    let filepath = path.join(targetdir, name)
    let modname = name.replace(/\ /g, '_')
    let outpath = path.join(outdir, modname)

    console.log('starting', filepath)

    gm(filepath)
      .resize(900, 600)
      .noProfile()
      .write(outpath, function (err) {
        if (err) throw err
        cb(null, outpath)
      });
  }

}

let tasks = images.map(resize)
parallelLimit(tasks, 10, console.log)


